language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.5.0
  - 2.4.1
  - 2.3.3
  - 2.2.7

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

before_install:
   - gem install bundler

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
